# Generated by Django 5.2.8 on 2025-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCoordenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=30)),
                ('carga_horaria', models.IntegerField()),
                ('nome_curso', models.CharField(max_length=300)),
                ('codigo_curso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=150)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=90)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
    ]
