# Generated by Django 5.2.8 on 2025-11-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.CharField(max_length=500)),
                ('nota', models.FloatField()),
                ('data_avaliacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField()),
                ('versao', models.FloatField()),
                ('nome_arquivo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('analise', 'Em análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.instituicao')),
            ],
        ),
    ]
