# Generated by Django 5.2.8 on 2025-11-21 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenador', '0002_initial'),
        ('estagio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.supervisor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.cursocoordenador'),
        ),
        migrations.AddField(
            model_name='documento',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.supervisor'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.empresa'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.supervisor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.estagio'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.estagio'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estagio.estagio'),
        ),
    ]
