# Generated by Django 5.2.8 on 2025-11-24 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 24, 19, 36, 44, 783877, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='observacoes_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='estagio.documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='prazo_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('ajustes_solicitados', 'Ajustes solicitados'), ('corrigido', 'Corrigido'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('substituido', 'Substituído')], default='enviado', max_length=30),
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
