# Generated by Django 5.2.8 on 2025-11-24 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0004_documento_aprovado_por_documento_data_aprovacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('ajustes_solicitados', 'Ajustes solicitados'), ('corrigido', 'Corrigido'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('substituido', 'Substituído'), ('finalizado', 'Finalizado')], default='enviado', max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('enviado', 'Documento Enviado'), ('aprovado', 'Aprovado pelo Supervisor'), ('reprovado', 'Reprovado pelo Supervisor'), ('ajustes_solicitados', 'Ajustes Solicitados'), ('corrigido', 'Documento Corrigido'), ('finalizado', 'Aprovado pelo Coordenador')], max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='estagio.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Documento',
                'verbose_name_plural': 'Históricos de Documentos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
