# Generated by Django 6.0 on 2025-12-15 22:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0002_initial'),
        ('estagio', '0005_alter_documento_status_documentohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='estagio.aluno')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='estagio.estagio')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_dados', to='coordenador.supervisor')),
            ],
            options={
                'verbose_name': 'Feedback do Supervisor',
                'verbose_name_plural': 'Feedbacks do Supervisor',
                'ordering': ['-data_feedback'],
            },
        ),
        migrations.CreateModel(
            name='HorasCumpridas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='estagio.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('destinatario', 'assunto', 'referencia')},
            },
        ),
    ]
