# Generated by Django 6.0 on 2025-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0006_feedbacksupervisor_horascumpridas_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='status',
            field=models.CharField(choices=[('analise', 'Em análise'), ('em_andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=20),
        ),
    ]
