# Generated by Django 6.0 on 2025-12-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0007_alter_estagio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='aluno_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estagios_solicitados', to='estagio.aluno'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estagio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
