# Generated by Django 6.0.1 on 2026-02-03 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0002_initial'),
        ('estagio', '0008_estagio_aluno_solicitante_estagio_data_solicitacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField(default=1.0, help_text='Peso do critério no cálculo da nota final')),
                ('nota_minima', models.FloatField(default=0)),
                ('nota_maxima', models.FloatField(default=10)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-data_envio']},
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='estagio.aluno'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_emissao_parecer',
            field=models.DateTimeField(blank=True, help_text='Data e hora da emissão do parecer final', null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota_final',
            field=models.FloatField(blank=True, help_text='Nota final calculada automaticamente - CA4', null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='parecer_disponivel_consulta',
            field=models.BooleanField(default=False, help_text='Indica se o parecer está disponível para consulta pelo aluno - CA6'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='parecer_final',
            field=models.TextField(blank=True, help_text='Parecer final obrigatório emitido pelo supervisor - CA5', null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('final', 'Avaliação Final')], default='mensal', max_length=20),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo_fim',
            field=models.DateField(blank=True, help_text='Data de fim do período avaliado', null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='periodo_inicio',
            field=models.DateField(blank=True, help_text='Data de início do período avaliado', null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('completa', 'Completa'), ('enviada', 'Enviada'), ('parecer_emitido', 'Parecer Emitido')], default='rascunho', max_length=20),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estagio',
            name='status_vaga',
            field=models.CharField(choices=[('disponivel', 'Vaga Disponível'), ('ocupada', 'Vaga Ocupada'), ('encerrada', 'Vaga Encerrada')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='estagio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='estagio.estagio'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('estagio', 'aluno', 'periodo_inicio', 'periodo_fim')},
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_realizacao', models.DateField()),
                ('horas_dedicadas', models.PositiveIntegerField(help_text='Horas dedicadas à atividade')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Confirmação'), ('confirmada', 'Confirmada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('justificativa_rejeicao', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='estagio.aluno')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_confirmadas', to='coordenador.supervisor')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='estagio.estagio')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_realizacao', '-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('registrada', 'Atividade Registrada'), ('confirmada', 'Atividade Confirmada'), ('rejeitada', 'Atividade Rejeitada')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='estagio.atividade')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordenador.supervisor')),
            ],
            options={
                'verbose_name': 'Histórico de Atividade',
                'verbose_name_plural': 'Históricos de Atividades',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='VinculoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('vinculado', 'Aluno Vinculado'), ('desvinculado', 'Aluno Desvinculado'), ('transferido', 'Aluno Transferido')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_vinculos', to='estagio.aluno')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_vinculos', to='estagio.estagio')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Vínculo',
                'verbose_name_plural': 'Históricos de Vínculos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='NotaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_criterios', to='estagio.avaliacao')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.criterioavaliacao')),
            ],
            options={
                'verbose_name': 'Nota de Critério',
                'verbose_name_plural': 'Notas de Critérios',
                'unique_together': {('avaliacao', 'criterio')},
            },
        ),
    ]
