# Generated by Django 6.0.1 on 2026-02-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_delete_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Nível')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('permissoes', models.ManyToManyField(blank=True, related_name='niveis_acesso', to='auth.permission', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Nível de Acesso',
                'verbose_name_plural': 'Níveis de Acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.nivelacesso', verbose_name='Nível de Acesso'),
        ),
    ]
