# Generated by Django 6.0.2 on 2026-02-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_nivelacesso_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('aluno', 'Aluno'), ('supervisor', 'Supervisor'), ('coordenador', 'Curso Coordenador')], max_length=20),
        ),
    ]
